title: Cybersecurity Library  # e.g., PBMunds Docs
description: Dynamic Documentation and Blog
url: "https://pbmunds.github.io/library"
logo: /assets/logo.png  # Path to your logo image (upload later)
theme: minima
plugins:
  - jekyll-feed
header_pages:  # Pages to show in top nav if needed
  - about.md
collections:
  docs:  # Custom collection for documentation posts
    output: true
    permalink: /:collection/:path/
include: ['_pages']  # If you have non-post pages
collections:
  pages:
    output: true
defaults:
  - scope:
      path: ""
      type: docs
    values:
      layout: doc
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
    values:
      layout: "default"
