site_name: My Library
site_url: https://pbmundas.github.io/library/
theme:
  name: material
  features:
    - navigation.sections  # Enables collapsible groups in sidebar
    - navigation.expand    # Expands sections by default
    - search.suggest       # Adds search suggestions
    - search.highlight     # Highlights search terms
    - search.share         # Allows sharing search queries
plugins:
  - search              # Built-in search bar
  - tags                # For category-like tagging
markdown_extensions:
  - attr_list           # For advanced Markdown attributes
  - md_in_html          # Embed Markdown in HTML
nav:
  - Home: index.md
  - Categories:         # Placeholder for dynamic categories
      - Category 1: category1/index.md
extra:
  tags: {}              # Optional: Map tags to icons here
